# Generated by Django 5.2.5 on 2025-09-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('beginner', 'beginner'), ('wanna_be', 'wanna_be'), ('enthusiast', 'enthusiast')], default='beginner', max_length=10),
        ),
    ]
