# Generated by Django 4.2.23 on 2025-12-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
