# Generated by Django 4.2.23 on 2025-12-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pending_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
