# Generated by Django 4.2.23 on 2026-01-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
